# Generated by Django 5.1.5 on 2025-01-16 17:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.IntegerField(choices=[(5, 'Draft'), (10, 'Published')], default=5)),
                ('body', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, '1 - Bad'), (2, '2 -Poor'), (3, '3 - Fair'), (4, '4 - Good'), (5, '5 - Excellent'), (6, '6 -Exceptional')], default=3)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
