# Generated by Django 5.1.5 on 2025-01-16 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='author_id',
            new_name='author',
        ),
    ]
